apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: memory-database
    app: voting-app
    name: redis
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
