apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    tier: frontend
    name: voting-app
    app: voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
