apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    tier: backend
    name: worker-app
    app: voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
